//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 02:58:55 PM CEST 
//


package org.w3._2006._01.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2006._01.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Property_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "property");
    private final static QName _Description_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "description");
    private final static QName _Binding_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "binding");
    private final static QName _Interface_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "interface");
    private final static QName _Types_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "types");
    private final static QName _Endpoint_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "endpoint");
    private final static QName _Include_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "include");
    private final static QName _Service_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "service");
    private final static QName _Documentation_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "documentation");
    private final static QName _Import_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "import");
    private final static QName _Feature_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "feature");
    private final static QName _BindingTypeFault_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "fault");
    private final static QName _BindingTypeOperation_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "operation");
    private final static QName _InterfaceOperationTypeOutfault_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "outfault");
    private final static QName _InterfaceOperationTypeInfault_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "infault");
    private final static QName _InterfaceOperationTypeOutput_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "output");
    private final static QName _InterfaceOperationTypeInput_QNAME = new QName("http://www.w3.org/2006/01/wsdl", "input");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2006._01.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IncludeType }
     * 
     */
    public IncludeType createIncludeType() {
        return new IncludeType();
    }

    /**
     * Create an instance of {@link TypesType }
     * 
     */
    public TypesType createTypesType() {
        return new TypesType();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link ImportType }
     * 
     */
    public ImportType createImportType() {
        return new ImportType();
    }

    /**
     * Create an instance of {@link FeatureType }
     * 
     */
    public FeatureType createFeatureType() {
        return new FeatureType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link DocumentationType }
     * 
     */
    public DocumentationType createDocumentationType() {
        return new DocumentationType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link BindingType }
     * 
     */
    public BindingType createBindingType() {
        return new BindingType();
    }

    /**
     * Create an instance of {@link InterfaceType }
     * 
     */
    public InterfaceType createInterfaceType() {
        return new InterfaceType();
    }

    /**
     * Create an instance of {@link MessageRefFaultType }
     * 
     */
    public MessageRefFaultType createMessageRefFaultType() {
        return new MessageRefFaultType();
    }

    /**
     * Create an instance of {@link InterfaceOperationType }
     * 
     */
    public InterfaceOperationType createInterfaceOperationType() {
        return new InterfaceOperationType();
    }

    /**
     * Create an instance of {@link BindingOperationType }
     * 
     */
    public BindingOperationType createBindingOperationType() {
        return new BindingOperationType();
    }

    /**
     * Create an instance of {@link BindingOperationMessageType }
     * 
     */
    public BindingOperationMessageType createBindingOperationMessageType() {
        return new BindingOperationMessageType();
    }

    /**
     * Create an instance of {@link MessageRefType }
     * 
     */
    public MessageRefType createMessageRefType() {
        return new MessageRefType();
    }

    /**
     * Create an instance of {@link InterfaceFaultType }
     * 
     */
    public InterfaceFaultType createInterfaceFaultType() {
        return new InterfaceFaultType();
    }

    /**
     * Create an instance of {@link BindingFaultType }
     * 
     */
    public BindingFaultType createBindingFaultType() {
        return new BindingFaultType();
    }

    /**
     * Create an instance of {@link DocumentedType }
     * 
     */
    public DocumentedType createDocumentedType() {
        return new DocumentedType();
    }

    /**
     * Create an instance of {@link BindingOperationFaultType }
     * 
     */
    public BindingOperationFaultType createBindingOperationFaultType() {
        return new BindingOperationFaultType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "property")
    public JAXBElement<PropertyType> createProperty(PropertyType value) {
        return new JAXBElement<PropertyType>(_Property_QNAME, PropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "description")
    public JAXBElement<DescriptionType> createDescription(DescriptionType value) {
        return new JAXBElement<DescriptionType>(_Description_QNAME, DescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "binding")
    public JAXBElement<BindingType> createBinding(BindingType value) {
        return new JAXBElement<BindingType>(_Binding_QNAME, BindingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "interface")
    public JAXBElement<InterfaceType> createInterface(InterfaceType value) {
        return new JAXBElement<InterfaceType>(_Interface_QNAME, InterfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "types")
    public JAXBElement<TypesType> createTypes(TypesType value) {
        return new JAXBElement<TypesType>(_Types_QNAME, TypesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndpointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "endpoint")
    public JAXBElement<EndpointType> createEndpoint(EndpointType value) {
        return new JAXBElement<EndpointType>(_Endpoint_QNAME, EndpointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncludeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "include")
    public JAXBElement<IncludeType> createInclude(IncludeType value) {
        return new JAXBElement<IncludeType>(_Include_QNAME, IncludeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "service")
    public JAXBElement<ServiceType> createService(ServiceType value) {
        return new JAXBElement<ServiceType>(_Service_QNAME, ServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "documentation")
    public JAXBElement<DocumentationType> createDocumentation(DocumentationType value) {
        return new JAXBElement<DocumentationType>(_Documentation_QNAME, DocumentationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "import")
    public JAXBElement<ImportType> createImport(ImportType value) {
        return new JAXBElement<ImportType>(_Import_QNAME, ImportType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "feature")
    public JAXBElement<FeatureType> createFeature(FeatureType value) {
        return new JAXBElement<FeatureType>(_Feature_QNAME, FeatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "fault", scope = BindingType.class)
    public JAXBElement<BindingFaultType> createBindingTypeFault(BindingFaultType value) {
        return new JAXBElement<BindingFaultType>(_BindingTypeFault_QNAME, BindingFaultType.class, BindingType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingOperationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "operation", scope = BindingType.class)
    public JAXBElement<BindingOperationType> createBindingTypeOperation(BindingOperationType value) {
        return new JAXBElement<BindingOperationType>(_BindingTypeOperation_QNAME, BindingOperationType.class, BindingType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageRefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "outfault", scope = InterfaceOperationType.class)
    public JAXBElement<MessageRefFaultType> createInterfaceOperationTypeOutfault(MessageRefFaultType value) {
        return new JAXBElement<MessageRefFaultType>(_InterfaceOperationTypeOutfault_QNAME, MessageRefFaultType.class, InterfaceOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageRefFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "infault", scope = InterfaceOperationType.class)
    public JAXBElement<MessageRefFaultType> createInterfaceOperationTypeInfault(MessageRefFaultType value) {
        return new JAXBElement<MessageRefFaultType>(_InterfaceOperationTypeInfault_QNAME, MessageRefFaultType.class, InterfaceOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "output", scope = InterfaceOperationType.class)
    public JAXBElement<MessageRefType> createInterfaceOperationTypeOutput(MessageRefType value) {
        return new JAXBElement<MessageRefType>(_InterfaceOperationTypeOutput_QNAME, MessageRefType.class, InterfaceOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "input", scope = InterfaceOperationType.class)
    public JAXBElement<MessageRefType> createInterfaceOperationTypeInput(MessageRefType value) {
        return new JAXBElement<MessageRefType>(_InterfaceOperationTypeInput_QNAME, MessageRefType.class, InterfaceOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "fault", scope = InterfaceType.class)
    public JAXBElement<InterfaceFaultType> createInterfaceTypeFault(InterfaceFaultType value) {
        return new JAXBElement<InterfaceFaultType>(_BindingTypeFault_QNAME, InterfaceFaultType.class, InterfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InterfaceOperationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "operation", scope = InterfaceType.class)
    public JAXBElement<InterfaceOperationType> createInterfaceTypeOperation(InterfaceOperationType value) {
        return new JAXBElement<InterfaceOperationType>(_BindingTypeOperation_QNAME, InterfaceOperationType.class, InterfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingOperationFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "outfault", scope = BindingOperationType.class)
    public JAXBElement<BindingOperationFaultType> createBindingOperationTypeOutfault(BindingOperationFaultType value) {
        return new JAXBElement<BindingOperationFaultType>(_InterfaceOperationTypeOutfault_QNAME, BindingOperationFaultType.class, BindingOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingOperationFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "infault", scope = BindingOperationType.class)
    public JAXBElement<BindingOperationFaultType> createBindingOperationTypeInfault(BindingOperationFaultType value) {
        return new JAXBElement<BindingOperationFaultType>(_InterfaceOperationTypeInfault_QNAME, BindingOperationFaultType.class, BindingOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingOperationMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "output", scope = BindingOperationType.class)
    public JAXBElement<BindingOperationMessageType> createBindingOperationTypeOutput(BindingOperationMessageType value) {
        return new JAXBElement<BindingOperationMessageType>(_InterfaceOperationTypeOutput_QNAME, BindingOperationMessageType.class, BindingOperationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BindingOperationMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2006/01/wsdl", name = "input", scope = BindingOperationType.class)
    public JAXBElement<BindingOperationMessageType> createBindingOperationTypeInput(BindingOperationMessageType value) {
        return new JAXBElement<BindingOperationMessageType>(_InterfaceOperationTypeInput_QNAME, BindingOperationMessageType.class, BindingOperationType.class, value);
    }

}
